server:
  port: 7005
spring:
  application:
    name: eureka-client-consumer-01-7005
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.56:7001/eureka/,http://192.168.0.56:7002/eureka/
server-url:
  userServer: SERVER-PROVIDER-01-7004