server:
  port: 7002
spring:
  application:
    name: eureka-server-7002
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.93.1:7001/eureka/