server:
  port: 7004
spring:
  application:
    name: server-provider-01-7004
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.0.56:7001/eureka/,http://192.168.0.56:7002/eureka/